#!/bin/bash

###### KILL ######
kill-hlf () {
	docker-compose down 
	containers=$(docker ps -q) && docker kill $containers
	docker network prune -f && docker volume prune -f
}

# #kill other dockers 
cd blockchainexplorer
kill-hlf
cd ../artifacts
kill-hlf
